version: 2
 jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
 
    steps:
      - checkout
 
    - run:
      name: build dependences
      command: bundle install
 
    - run:
      name: build the jekyll site
      command: bundle exec jekyll build
 
     - run:
      print: Print the Current Time
      command: date
